
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tg?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Harnas1988!
  jpa:
    show-sql: true
  sql:
    init:
      mode: always